public class ArrayIndexOutOfBoundsExceptions {
    public static void main(String[] args) {
        int[] array = {1, 2, 3, 4, 5};

        try {
            int element = array[10];
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Exception: Accessing an array element outside its bound.");
        }

        try {
            for (int i = 0; i <= array.length; i++) {
                System.out.println(array[i]);
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Exception: Iterating beyond the array length.");
        }

        int[][] nestedArray = {{1, 2, 3}, {4, 5, 6}};
        
        try {
            int nestedElement = nestedArray[2][1];
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Exception: Accessing nested array with incorrect index.");
        }

        try {
            processArray(null);
        } catch (NullPointerException e) {
            System.out.println("Exception: Passing incorrect array to the method.");
        }
    }

    public static void processArray(int[] arr) {
        try {
            int element = arr[0];
        } catch (NullPointerException e) {
            throw new NullPointerException("Array is null.");
        }
    }
}
